name: Build IceCream

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          architecture: x64
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          ./gradlew applyPatches --stacktrace
      - name: Create Paperclip Jar
        run: ./gradlew createPaperclipJar --stacktrace
      - name: Upload Artifacts
        if: env.debug == 'true' || github.ref_name != env.branch
        uses: actions/upload-artifact@main
        with:
          name: Artifacts
          path: server/build/libs
      - name: Create Release
        uses: ncipollo/release-action@v1.15.0
        with:
          artifacts: server/build/libs
          bodyFile: server/build/libs/IceCream-paperclip-1.21.4-SNAPSHOT.jar
          tag: ${{ env.tag }}
          name: ${{ env.name }}
          prerelease: ${{ env.experimental }}
          token: ${{ secrets.TOKEN }}
          makeLatest: ${{ env.make_latest }}
      - name: Publish to Repo
        run: ./gradlew publish -PICECREAMUsername=${{ secrets.MAVEN_USER }} -PICECREAMPassword=${{ secrets.MAVEN_SECRET }}
        continue-on-error: true
