name: Build IceCream

on:
  push:
    tags:
    - '*'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          architecture: x64
      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Apply Patches        
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          ./gradlew applyPatches --stacktrace
      - name: Create Paperclip Jar
        run: ./gradlew createPaperclipJar --stacktrace
      - name: Create Release
        continue-on-error: true
        uses: ncipollo/release-action@v1
        with:
          artifacts: server/build/libs/IceCream-paperclip-1.21.4-SNAPSHOT.jar
          tag: v${{ github.run_number }} 
          name: Build ${{ github.run_number }}
          prerelease: false
          token: ${{ secrets.TOKEN }}
          makeLatest: true
      - name: Publish to Repo
        run: ./gradlew publish -PICECREAMUsername=${{ secrets.MAVEN_USER }} -PICECREAMPassword=${{ secrets.MAVEN_SECRET }}
        continue-on-error: true
